spring:
  application:
    name: colab-service
  datasource:
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5440/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true